### PR TITLE
Fix extension endpoints

### LINKED ISSUE #38: Setup Extension endpoints

### PR DESCRIPTION
**Pull request by louisheal**

### CODE REVIEW

File: config/auth.go [hunk 1]
```diff
@@ -1,16 +1,21 @@
...
+	"encoding/base64"
+
 	"github.com/streampets/backend/repositories"
 	"github.com/streampets/backend/services"
 	"gorm.io/gorm"
 )
 
 func CreateAuthService(db *gorm.DB) *services.AuthService {
-	clientSecret := mustGetEnv("CLIENT_SECRET")
+	extensionSecret, err := base64.StdEncoding.DecodeString(mustGetEnv("EXTENSION_SECRET"))
```
Comment (louisheal) [inline config/auth.go:12]: Should `mustGetEnv("EXTENSION_SECRET")` be its own variable?

File: config/auth.go [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
+	if err != nil {
+		panic(err)
+	}
 
 	channelRepo := repositories.NewChannelRepo(db)
-	authService := services.NewAuthService(channelRepo, clientSecret)
+	authService := services.NewAuthService(channelRepo, string(extensionSecret))
```
Comment (louisheal) [inline config/auth.go:18]: Should `string(extensionSecret)` be its own variable?

File: repositories/item.go [hunk 3]
```diff
@@ -82,6 +84,11 @@ func (repo *itemRepository) AddOwnedItem(userID models.TwitchID, itemID, transac
 		return result.Error
 	}
 
+	// TODO: How frowned upon is this?
+	if os.Getenv("ENVIRONMENT") == "DEVELOPMENT" {
```
Comment (louisheal) [inline repositories/item.go:87]: Is it reasonable to leave this in production code?

Comment (louisheal) [reply repositories/item.go:87]: Going to leave this in

File: config/auth.go (hunk 1 above)
Comment (louisheal) [reply config/auth.go:12]: Decided that this would be unnecessary

File: config/auth.go (hunk 2 above)
Comment (louisheal) [reply config/auth.go:18]: Decided that this would be unnecessary
